// <auto-generated />
namespace Systrade.Clientes.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Cliente01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cliente01));
        
        string IMigrationMetadata.Id
        {
            get { return "201805310403408_Cliente-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
